/*
 * Splash_Screen Implementation - 3-second branded boot splash
 * Shows CAMAZOTZ (Aztec font), bat/sonar logo, IXCHEL (bold sans-serif)
 */

#include "utils/splash_screen.hpp"
#include "lvgl.h"
#include "pico/stdlib.h"
#include "hardware/watchdog.h"
#include <cstdio>

/* External font declarations (generated by lv_font_conv) */
LV_FONT_DECLARE(font_quetzalcoatl_32)
LV_FONT_DECLARE(font_montserrat_bold_32)

/* External image declaration (generated from logo2.png) */
extern const lv_img_dsc_t logo_img;

/* Gap between logo and text labels */
static constexpr int16_t TEXT_GAP = 15;

/* Cream/warm white for title text */
static const lv_color_t COLOR_CREAM = LV_COLOR_MAKE(0xFF, 0xF0, 0xE0);

void show_splash_screen(uint32_t duration_ms) {
    /* Save the AMOLED default screen so we can restore it after splash.
     * Deleting the active screen without restoring leaves lv_scr_act() dangling,
     * which crashes all subsequent LVGL calls (show_status, clear, etc.). */
    lv_obj_t *prev_screen = lv_scr_act();

    /* Create splash screen */
    lv_obj_t *screen = lv_obj_create(nullptr);
    lv_obj_set_style_bg_color(screen, lv_color_black(), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, LV_PART_MAIN);

    /* Compass logo - centered on screen */
    lv_obj_t *logo = lv_img_create(screen);
    lv_img_set_src(logo, &logo_img);
    lv_obj_align(logo, LV_ALIGN_CENTER, 0, 0);

    /* "CAMAZOTZ" title - Aztec-style font, cream color, just above logo */
    lv_obj_t *title = lv_label_create(screen);
    lv_label_set_text(title, "CAMAZOTZ");
    lv_obj_set_style_text_color(title, COLOR_CREAM, LV_PART_MAIN);
    lv_obj_set_style_text_font(title, &font_quetzalcoatl_32, LV_PART_MAIN);
    lv_obj_align_to(title, logo, LV_ALIGN_OUT_TOP_MID, 0, -TEXT_GAP);

    /* "IXCHEL" subtitle - Montserrat Bold, white, just below logo */
    lv_obj_t *subtitle = lv_label_create(screen);
    lv_label_set_text(subtitle, "IXCHEL");
    lv_obj_set_style_text_color(subtitle, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(subtitle, &font_montserrat_bold_32, LV_PART_MAIN);
    lv_obj_align_to(subtitle, logo, LV_ALIGN_OUT_BOTTOM_MID, 0, TEXT_GAP);

    /* Activate splash screen */
    lv_scr_load(screen);

    /* Run LVGL task handler in loop for the requested duration.
     * 50ms interval keeps USB CDC alive (TinyUSB needs periodic servicing). */
    uint32_t start = to_ms_since_boot(get_absolute_time());
    while ((to_ms_since_boot(get_absolute_time()) - start) < duration_ms) {
        lv_task_handler();
        watchdog_update();
        sleep_ms(50);
    }

    /* Restore the previous screen before deleting splash.
     * This ensures lv_scr_act() returns a valid screen for subsequent code. */
    lv_scr_load(prev_screen);
    lv_obj_del(screen);
}
